### ISSUE TITLE
We don't need to bundle external modules

### ISSUE THREAD

**Issue by phobson** [Geosyntec/wqreports#2]
Just fork to Geosyntec's account, make a `develop` branch, make the changes there, and I'll install it into the WinPython env.

**Comment by lucashtnguyen** [comment]
That might be unavoidable with `pdfkit`, as it needs to reference a specific path to the wkhtmltopdf.exe. Currently this is accomplished by referencing the script's file path where the .exe is also located:

```
CURRENTDIR = os.path.dirname(os.path.realpath(__file__))

os.path.join(CURRENTDIR, 'wkhtmltopdf.exe')
```

I can leave as is, or create a folk and let you reassign the path of the .exe?

The `wkhtmltopdf` module is no longer needed.

**Comment by phobson** [comment]
See how I reference the testdata file in the PR with the tests. We could reference it that way. 

—
