### ISSUE TITLE
Need a simple command-line interface

### ISSUE THREAD

**Issue by phobson** [Geosyntec/wqreports#7]
I don't know if that's a `.bat` file that looks for all local text file or what. But it needs to be dead simple to use.

**Comment by lucashtnguyen** [comment]
Paul, take a look at the last commit and let me know if that's dead simple enough. The bat file will need to locally reference `batchrun.py`

**Comment by lucashtnguyen** [comment]
Also, you might want to change line 3 of `run.bat` to:

```
python %0\..\batchrun.py %*
```

if you want 'click ability' of the .bat file, assuming `batchrun.py` comes along for the ride
